version: '3.7'
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - $APP_PORT:$APP_PORT
    environment:
      APP_PORT: $APP_PORT
      PG_HOST: $PG_HOST
      PG_PORT: $PG_PORT
      PG_DATABASE: $PG_DATABASE
      PG_USER: $PG_USER
      PG_PASSWORD: $PG_PASSWORD
      PG_TEST_HOST: $PG_TEST_HOST
      PG_TEST_PORT: $PG_TEST_PORT
      PG_TEST_DATABASE: $PG_TEST_DATABASE
      PG_TEST_USER: $PG_TEST_USER
      PG_TEST_PASSWORD: $PG_TEST_PASSWORD
